include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/**
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    unawaited_futures: true
    avoid_print: true
